"""
Loads feature importance data from the precomputed JSON.
The JSON was generated by precompute_feature_importance.py using gradient * input attribution.
"""
import json
from pathlib import Path


def load_feature_importance(precomputed_dir: Path) -> dict:
    path = precomputed_dir / "bitcoin_feature_importance.json"
    with open(path) as f:
        return json.load(f)


def get_top_features(tx_id: str, importance_data: dict, top_k: int = 10) -> list[dict]:
    """Returns the top-k feature importance entries for a given transaction."""
    return importance_data.get(tx_id, [])[:top_k]
